name: ECS Deployment

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 581628381182
  ECS_CLUSTER_NAME: sneaky-fit-frontend-cluster
  ECS_SERVICE_NAME: sneaky-fit-frontend-service
  ECR_REPO_NAME: sneaky-fit-frontend
  ECS_TASK_DEF_NAME: sneaky-fit-frontend-td
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          echo ${{ secrets.AWS_ACCESS_KEY_ID }} | docker login -u AWS --password-stdin ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t ${{ env.ECR_REPO_NAME }}:$GITHUB_SHA .
          docker tag ${{ env.ECR_REPO_NAME }}:$GITHUB_SHA ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:$GITHUB_SHA

      - name: Push Docker image to Amazon ECR
        run: |
          docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO_NAME }}:$GITHUB_SHA

      - name: Fetch ECS Task Definition
        run: |
          aws ecs describe-task-definition \
            --task-definition ${{ env.ECS_TASK_DEF_NAME }} \
            --query 'taskDefinition' \
            --output json > task-def.json

      - name: Update ECS Task Definition
        id: update-task-def
        run: |
          task_def_arn=$(aws ecs register-task-definition \
            --family your-ecs-task-family \
            --container-definitions "$(cat task-def.json)" \
            --query 'taskDefinition.taskDefinitionArn' \
            --output text)
          echo "Task Definition ARN: $task_def_arn"
          echo "::set-output name=task_def_arn::$task_def_arn"

      - name: Deploy to ECS Service
        run: |
          ecs_service_name=${{ env.ECS_SERVICE_NAME }}
          ecs_cluster_name=${{ env.ECS_CLUSTER_NAME }}
          task_def_arn=${{ steps.update-task-def.outputs.task_def_arn }}
          
          aws ecs update-service \
            --cluster $ecs_cluster_name \
            --service $ecs_service_name \
            --task-definition $task_def_arn
